spring.application.name=payment-service

# R2DBC
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/payment_db
spring.r2dbc.username=${DB_USERNAME}
spring.r2dbc.password=${DB_PASSWORD}

# Liquibase
spring.liquibase.url=jdbc:postgresql://localhost:5432/payment_db
spring.liquibase.user=${DB_USERNAME}
spring.liquibase.password=${DB_PASSWORD}
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Kafka
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.group-id=payment-service-group