spring.application.name=inquiry-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:${INQUIRY_POSTGRES_PORT}/${INQUIRY_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs