spring.application.name=customer-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:${CUSTOMER_POSTGRES_PORT}/${CUSTOMER_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.show-actuator=true

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=health,info,metrics,loggers,env,mappings
management.endpoints.web.exposure.exclude=heapdump,threaddump,shutdown
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true

# SQL / JPA logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=DEBUG
