spring.application.name=inventory-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:${INVENTORY_POSTGRES_PORT}/${INVENTORY_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

